---

    - name: "Creating blacbox user group"
      group: name="{{group_id}}"

    - name: "Creating blackbox user"
      user:
        name: "{{ group_id }}"
        group: "{{ user_id }}"
        system: yes
        shell: "/sbin/nologin"
        comment: "blackbox nologin User"
        createhome: "no"
        state: present

    - name: "download blackbox source"
      unarchive:
        src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: "Copy blackbox file to bin"
      copy:
        src: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64/blackbox_exporter"
        dest: "/usr/local/bin/blackbox_exporter"
        owner: "{{ user_id }}"
        group: "{{ group_id }}"
        mode: 0755
        remote_src: yes

    - name: "creat blackbox directory in /etc"
      file:
        path: "/etc/blackbox_exporter"
        state: directory
        owner: "{{ user_id }}"
        group: "{{ group_id }}"
        mode: 0755
        recurse: yes

    - name: "Copy blackbox config file to /etc/blackbox"
      copy:
        src: "blackbox.yml"
        dest: "/etc/blackbox_exporter/blackbox.yml"
        owner: "{{ user_id }}"
        group: "{{ group_id }}"
        mode: 0755

#   - name: "Delete blackbox tmp folder"
#      file:
#        path: '/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64'
#        state: absent

    - name: "copy blackbox service-unit file to /etc/systemd/system/"
      copy:
        src: "blackbox_exporter.service"
        dest: "/etc/systemd/system/blackbox_exporter.service"

    - name: "restart daemon , enable and then start blackbox_exporter.service"
      systemd:
        name: blackbox_exporter.service
        daemon_reload: yes
        enabled: yes
        state: started
