---
  - name: templating files to remotes
    become: true 
    template:
      src: "{{ item }}.j2"
      dest: "/tmp/{{ item }}.txt"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0700
    loop:
      - instance
      - properties