---

    - name: "Creating Node_Exporter user group"
      group: name="{{group_id}}"

    - name: "Creating Node_Exporter user"
      user:
        name: "{{ group_id }}"
        group: "{{ user_id }}"
        system: yes
        shell: "/sbin/nologin"
        comment: "node_exporter nologin User"
        createhome: "no"
        state: present

    - name: "download Node_Exporter source"
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: "Copy Node_Exporter binary to bin"
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        owner: "{{ user_id }}"
        group: "{{ group_id }}"
        mode: 0755
        remote_src: yes

#    - name: "Delete node_exporter tmp folder"
#      file:
#        path: '/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64'
#        state: absent

    - name: "copy Node_Exporter service-unit file to /etc/systemd/system/"
      copy:
        src: "node_exporter.service"
        dest: "/etc/systemd/system/node_exporter.service"

    - name: "restart daemon , enable and then start node_exporter.service"
      systemd:
        name: node_exporter.service
        daemon_reload: yes
        enabled: yes
        state: started

