---
# tasks file for ufw

    - name: UFW - allow 9100 to prometheus
      ufw:
        rule: allow
        port: 9126
        proto: tcp
        src: 172.19.160.14
        comment: Allow prom to node.exporter
        policy: allow
        state: reloaded
      tags: "ufw"

