---
# tasks file for telegraf
    - name: install transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: add telegraf apt-key
      apt_key:
        url: https://repos.influxdata.com/influxdb.key
        state: present

    - name: add telegraf apt repository
      apt_repository:
        repo: 'deb https://repos.influxdata.com/ubuntu trusty stable'
        state: present
        filename: influx
        update_cache: yes

    - name: install telegraf
      apt:
        name: telegraf
        state: present

    - name: "enable and then start telegraf service"
      systemd:
        name: telegraf
        enabled: yes
        state: started

